"use client";

import {useEffect,useMemo,useState} from "react";
import {
 AlertCircle,AlertTriangle,ArrowLeft,BarChart3,Bell,Camera,Check,CheckCircle2,
 ChevronRight,ClipboardCheck,Clock,FileText,Filter,Home,LogOut,MapPin,Menu,
 Bot,ImagePlus,Plus,RefreshCw,School,Search,Send,Settings,ShieldCheck,Upload,UserCog,Users,X
} from "lucide-react";

type Party={name:string;votes:number|null};
type Ocr={school:string;ballotBox:string;district:string;neighborhood:string;registeredVoters:number|null;voters:number|null;validVotes:number|null;invalidVotes:number|null;parties:Party[];confidence:number;warnings:string[]};
type Screen="portal"|"dashboard"|"drilldown"|"ballots"|"ballot"|"morning"|"incidents"|"incidentNew"|"results"|"ocr"|"users"|"notifications"|"profile";
type Role="school"|"neighborhood"|"district";
type Account={username:string;name:string;role:Role;school?:string;neighborhood?:string};
type IncidentRecord={id:string;category:string;priority:string;description:string;party:string;votes:string;status:"Açık"|"Çözüldü";createdBy:string;createdAt:string;resolvedAt?:string};
type Ballot={id:string;school:string;neighborhood:string;officer:string;morning:string;voting:string;counting:string;result:string;incidents:number;incidentRecords:IncidentRecord[];critical:boolean;updated:string;votes:number;invalid:number;parties:Record<string,number>};
type Timeline={title:string;who:string;time:string;note?:string};

const blank:Ocr={school:"",ballotBox:"",district:"Kadıköy",neighborhood:"",registeredVoters:null,voters:null,validVotes:null,invalidVotes:null,parties:[],confidence:0,warnings:[]};
const neighborhoods=["Bostancı","Acıbadem","Caddebostan","Caferağa","Dumlupınar","Eğitim","Erenköy","Fenerbahçe","Feneryolu","Fikirtepe","Göztepe","Hasanpaşa","Koşuyolu","Kozyatağı","Merdivenköy","Osmanağa","Rasimpaşa","Sahrayıcedit","Suadiye","Zühtüpaşa","19 Mayıs"];
const schoolPairs:Record<string,[string,string]>={
 Bostancı:["Bostancı Atatürk İlkokulu","Bostancı Ortaokulu"],Acıbadem:["Acıbadem Türk Telekom Ortaokulu","Acıbadem İlkokulu"],Göztepe:["Göztepe İlkokulu","İlhami Ahmed Örnekal İlkokulu"],Koşuyolu:["Koşuyolu İlkokulu","Koşuyolu Kalp Hastanesi Eğitim Binası"]
};
const incidentSamples=[
 ["Bir parti veya adaya yazılan oya itiraz","Yüksek","CHP hanesine yazılan 3 oyun geçerliliğine müşahit tarafından itiraz edildi.","CHP","3"],
 ["Tutanak uyuşmazlığı","Kritik","Sayım döküm cetveli ile sandık sonuç tutanağındaki geçerli oy toplamı arasında 2 oy fark tespit edildi.","","2"],
 ["Mühür sorunu","Yüksek","Bir zarfın sandık kurulu mührünün okunaksız olduğu tutanak altına alındı.","","1"],
 ["Görevli eksikliği","Normal","Sabah eksik olan kurul üyesi yedek üye görevlendirilerek saat 07.48'de tamamlandı.","",""],
 ["Sayım uyuşmazlığı","Kritik","İkinci sayım talebi üzerine oylar yeniden tasnif ediliyor.","",""]
] as const;
const initialBallots:Ballot[]=Array.from({length:1050},(_,i)=>{
 const neighborhood=neighborhoods[Math.floor(i/50)],pair=schoolPairs[neighborhood]??[`${neighborhood} İlkokulu`,`${neighborhood} Ortaokulu`],school=pair[i%50<25?0:1];
 const entered=i<20,approved=i<3,parties:Record<string,number>=entered?{"CHP":140+i%9,"AK Parti":35+i%5,"TİP":25+i%4,"İYİ Parti":24+i%3,"Yeşil Sol Parti":9+i%3,"MHP":5+i%2}:{};
 const records:IncidentRecord[]=i<incidentSamples.length?[{id:`OLY-${i+1}`,category:incidentSamples[i][0],priority:incidentSamples[i][1],description:incidentSamples[i][2],party:incidentSamples[i][3],votes:incidentSamples[i][4],status:"Açık",createdBy:i<2?"İlçe Merkezi":"Okul Başkanı",createdAt:`${15+i}:4${i}`}]:[];
 return {id:String(1001+i),school,neighborhood,officer:"Görevli geldi",morning:"Hazırlık tamamlandı",voting:"Oy verme sona erdi",counting:i<20?"Sayım tamamlandı":i<988?"Sayım devam ediyor":"Sayım bekliyor",result:approved?"Onaylandı":entered?"Kullanıcı doğrulaması bekliyor":"Tutanak bekleniyor",incidents:records.length,incidentRecords:records,critical:records.some(x=>x.priority==="Kritik"),updated:i<20?`${i+1} dk önce`:"şimdi",votes:Object.values(parties).reduce((s,v)=>s+v,0),invalid:entered?4+i%5:0,parties};
});
const accounts:Account[]=[
 {username:"talha",name:"Talha Doğan",role:"district"},
 {username:"bostanci",name:"Bostancı Mahalle Başkanı",role:"neighborhood",neighborhood:"Bostancı"},
 {username:"ataturk",name:"Bostancı Atatürk Okul Başkanı",role:"school",neighborhood:"Bostancı",school:"Bostancı Atatürk İlkokulu"},
];
const roleName:Record<Role,string>={school:"Okul başkanı",neighborhood:"Mahalle başkanı",district:"İlçe admini"};
function transitionError(current:Ballot,patch:Partial<Ballot>){
 const next={...current,...patch};
 if(next.officer!=="Görevli geldi"&&(next.voting!=="Hazırlık devam ediyor"||next.counting!=="Sayım bekliyor"||next.votes>0))return "Görevli teyidi tamamlanmadan oy verme, sayım veya tutanak aşamasına geçilemez.";
 if(next.counting!=="Sayım bekliyor"&&next.voting!=="Oy verme sona erdi")return "Sayım ancak oy verme saat 17.00'de sona erdikten sonra başlatılabilir.";
 if(next.result==="Onaylandı"&&next.counting!=="Sayım tamamlandı")return "Sayım tamamlanmadan sonuç onaylanamaz.";
 return "";
}
const timeline:Timeline[]=[
 {title:"Sayım başladı",who:"Ayşe Yılmaz",time:"17:14",note:"Salon düzeni kontrol edildi."},
 {title:"Oy verme sona erdi",who:"Ayşe Yılmaz",time:"17:02"},
 {title:"İtiraz kaydedildi",who:"Mehmet Kaya",time:"15:46",note:"3 oyun geçerliliğine itiraz edildi."},
 {title:"Oy verme başladı",who:"Ayşe Yılmaz",time:"08:00"},
 {title:"Hazırlık tamamlandı",who:"Ayşe Yılmaz",time:"07:42"},
 {title:"Görevli geldi",who:"Ayşe Yılmaz",time:"07:18"},
];
export default function App(){
 const[logged,setLogged]=useState(false),[user,setUser]=useState(""),[pass,setPass]=useState(""),[err,setErr]=useState("");
 const[account,setAccount]=useState<Account>(accounts[0]);
 const[screen,setScreen]=useState<Screen>("portal"),[history,setHistory]=useState<Screen[]>([]);
 const[ballots,setBallots]=useState(initialBallots),[selectedId,setSelectedId]=useState("1001"),[caseTab,setCaseTab]=useState("Genel");
 const[metric,setMetric]=useState("Toplam sandık"),[query,setQuery]=useState(""),[filterOpen,setFilterOpen]=useState(false);
 const[toast,setToast]=useState(""),[modal,setModal]=useState<null|"user"|"settings"|"incident">(null);
 const[advisorOpen,setAdvisorOpen]=useState(false);
 const[image,setImage]=useState(""),[reading,setReading]=useState(false),[step,setStep]=useState(1),[ocr,setOcr]=useState<Ocr>(blank);
 const[incident,setIncident]=useState({category:"Bir parti veya adaya yazılan oya itiraz",priority:"Yüksek",description:"",party:"",votes:""});
 const canEdit=(b:Ballot)=>account.role==="district"||(account.role==="neighborhood"&&b.neighborhood===account.neighborhood)||(account.role==="school"&&b.school===account.school);
 const scopedBallots=useMemo(()=>ballots.filter(canEdit),[ballots,account]);
 const selected=ballots.find(x=>x.id===selectedId)??scopedBallots[0]??ballots[0];
 const filtered=useMemo(()=>scopedBallots.filter(x=>`${x.id} ${x.school} ${x.neighborhood} ${x.result}`.toLocaleLowerCase("tr").includes(query.toLocaleLowerCase("tr"))),[scopedBallots,query]);
 useEffect(()=>{const saved=localStorage.getItem("k360-session");const savedUser=localStorage.getItem("k360-user");if(saved==="on"){const found=accounts.find(x=>x.username===savedUser);if(found){setAccount(found);setLogged(true)}}const savedBallots=localStorage.getItem("k360-ballots-v3");if(savedBallots)try{setBallots(JSON.parse(savedBallots))}catch{}},[]);
 useEffect(()=>{localStorage.setItem("k360-ballots-v3",JSON.stringify(ballots))},[ballots]);
 function go(next:Screen){setHistory(h=>[...h,screen]);setScreen(next);window.scrollTo({top:0,behavior:"smooth"})}
 function back(){const h=[...history];const p=h.pop();setHistory(h);setScreen(p??"dashboard")}
 function login(e:React.FormEvent){e.preventDefault();const found=accounts.find(x=>x.username===user);if(found&&pass==="sivas1358"){setAccount(found);setLogged(true);setScreen("portal");localStorage.setItem("k360-session","on");localStorage.setItem("k360-user",found.username)}else setErr("Kullanıcı adı veya şifre hatalı.")}
 function notify(t:string){setToast(t);window.setTimeout(()=>setToast(""),2800)}
 function choose(f?:File){if(!f)return;const r=new FileReader();r.onload=()=>{setImage(String(r.result));setOcr(blank);setStep(1);setErr("")};r.readAsDataURL(f)}
 async function read(){setReading(true);setErr("");try{const r=await fetch("/api/ocr",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({image})});const d=await r.json();if(!r.ok)throw new Error(d.error);setOcr({...blank,...d,parties:Array.isArray(d.parties)?d.parties:[]});setStep(2)}catch(e){setErr(e instanceof Error?e.message:"Fotoğraf okunamadı.")}finally{setReading(false)}}
 function updateBallot(patch:Partial<Ballot>){if(!canEdit(selected)){notify("Bu sandıkta düzenleme yetkiniz yok.");return}const invalid=transitionError(selected,patch);if(invalid){notify(invalid);return}setBallots(xs=>xs.map(x=>x.id===selected.id?{...x,...patch,updated:"şimdi"}:x));notify("Sandık kaydı güncellendi; bağlı göstergeler yenilendi.")}
 function openBallot(id:string){setSelectedId(id);setCaseTab("Genel");go("ballot")}
 if(!logged)return <Login user={user} pass={pass} err={err} setUser={setUser} setPass={setPass} login={login}/>;
 return <div className="shell">
  <header><button className="iconBtn" onClick={()=>setModal("settings")}><Menu/></button><div className="brand"><i className="iyiSun">☀</i><b>İYİ KADIKÖY<span>360</span></b><small>İYİ Parti Kadıköy · Seçim Koordinasyon Merkezi</small></div><button className="headerBell" onClick={()=>go("notifications")}><Bell/>{scopedBallots.some(x=>x.incidents>0||x.result!=="Onaylandı")&&<i>{Math.min(99,scopedBallots.filter(x=>x.incidents>0||x.result!=="Onaylandı").length)}</i>}</button></header>
  {toast&&<div className="toast"><CheckCircle2/>{toast}</div>}
  <main className="content">
   {history.length>0&&screen!=="portal"&&<button className="back" onClick={back}><ArrowLeft/> Geri</button>}
   {screen==="portal"&&<Portal account={account} ballots={scopedBallots} go={go}/>}
   {screen==="dashboard"&&<Dashboard go={go} ballots={scopedBallots} account={account} openMetric={(m)=>{setMetric(m);go("drilldown")}}/>}
   {screen==="drilldown"&&<Drilldown metric={metric} ballots={filtered} query={query} setQuery={setQuery} openBallot={openBallot}/>}
   {screen==="ballots"&&<BallotList ballots={filtered} query={query} setQuery={setQuery} openBallot={openBallot} filterOpen={filterOpen} setFilterOpen={setFilterOpen}/>}
   {screen==="ballot"&&<BallotDetail ballot={selected} tab={caseTab} setTab={setCaseTab} update={updateBallot} go={go} timeline={timeline}/>}
   {screen==="morning"&&<Morning ballots={scopedBallots} update={(id,p)=>{const target=ballots.find(x=>x.id===id);if(!target||!canEdit(target)){notify("Bu sandıkta düzenleme yetkiniz yok.");return}const invalid=transitionError(target,p);if(invalid){notify(invalid);return}setSelectedId(id);setBallots(xs=>xs.map(x=>x.id===id?{...x,...p,updated:"şimdi"}:x));notify("Sabah kontrolü kaydedildi; özet güncellendi.")}} openBallot={openBallot}/>}
   {screen==="incidents"&&<Incidents ballots={scopedBallots} openBallot={openBallot} create={()=>go("incidentNew")}/>}
   {screen==="incidentNew"&&<IncidentForm ballots={scopedBallots} selectedId={selectedId} setSelectedId={setSelectedId} incident={incident} setIncident={setIncident} save={()=>{const target=ballots.find(x=>x.id===selectedId);if(!target||!canEdit(target)){notify("Bu sandıkta olay oluşturma yetkiniz yok.");return}if(!incident.description.trim()){notify("Açıklama alanı zorunlu.");return}const record:IncidentRecord={id:`OLY-${Date.now()}`,category:incident.category,priority:incident.priority,description:incident.description.trim(),party:incident.party.trim(),votes:incident.votes,status:"Açık",createdBy:account.name,createdAt:new Date().toLocaleTimeString("tr-TR",{hour:"2-digit",minute:"2-digit"})};setBallots(xs=>xs.map(x=>x.id===target.id?{...x,incidentRecords:[...(x.incidentRecords??[]),record],incidents:(x.incidentRecords??[]).filter(r=>r.status==="Açık").length+1,critical:x.critical||record.priority==="Kritik",updated:"şimdi"}:x));notify(`Sandık ${target.id} olayı açıklamasıyla kaydedildi.`);setIncident({...incident,description:"",party:"",votes:""});setScreen("incidents")}}/>}
   {screen==="results"&&<Results ballots={ballots} scoped={scopedBallots} account={account} go={go} openBallot={openBallot}/>}
   {screen==="ocr"&&<OcrFlow image={image} choose={choose} reading={reading} read={read} err={err} step={step} setStep={setStep} ocr={ocr} setOcr={setOcr} allowedBallots={scopedBallots} finish={()=>{const target=ballots.find(x=>x.id===ocr.ballotBox);if(!target||!canEdit(target)){notify("Bu sandık için tutanak yükleme yetkiniz yok.");return}const parties=Object.fromEntries(ocr.parties.filter(p=>p.name&&p.votes!==null).map(p=>[p.name,p.votes as number]));setBallots(xs=>xs.map(x=>x.id===ocr.ballotBox?{...x,result:"Onaylandı",counting:"Sayım tamamlandı",votes:ocr.validVotes??0,invalid:ocr.invalidVotes??0,parties,updated:"şimdi"}:x));notify(`Sandık ${ocr.ballotBox} sonucu kaydedildi; kümül sonuçlar güncellendi.`);setStep(6)}}/>}
   {screen==="users"&&(account.role==="district"?<UsersPage accounts={accounts} active={account} switchAccount={a=>{setAccount(a);localStorage.setItem("k360-user",a.username);setHistory([]);setScreen("dashboard");notify(`${a.name} profiline geçildi.`)}} edit={()=>setModal("user")} notify={notify}/>:<Empty text="Kullanıcı ve yetki yönetimi yalnızca ilçe adminine açıktır."/>)}
   {screen==="notifications"&&<Notifications ballots={scopedBallots} openBallot={openBallot}/>}
   {screen==="profile"&&<Profile account={account} accounts={accounts} scopeCount={scopedBallots.length} switchAccount={a=>{setAccount(a);localStorage.setItem("k360-user",a.username);setHistory([]);setScreen("dashboard");notify(`${a.name} profiline geçildi.`)}} logout={()=>{localStorage.removeItem("k360-session");localStorage.removeItem("k360-user");setLogged(false)}}/>}
  </main>
  <nav>
   <Nav active={screen==="dashboard"} on={()=>{setHistory([]);setScreen("dashboard")}} icon={<Home/>} text="Özet"/>
   <Nav active={screen==="ballots"||screen==="ballot"} on={()=>go("ballots")} icon={<FileText/>} text="Sandıklar"/>
   <Nav active={screen==="ocr"} on={()=>go("ocr")} icon={<Camera/>} text="Tutanak" center/>
   <Nav active={screen==="incidents"} on={()=>go("incidents")} icon={<AlertTriangle/>} text="Olaylar"/>
   <Nav active={screen==="profile"} on={()=>go("profile")} icon={<Users/>} text="Profil"/>
  </nav>
  <button className="advisorFab" onClick={()=>setAdvisorOpen(true)} aria-label="Seçim danışmanını aç"><Bot/><span>Seçim danışmanı</span></button>
  {advisorOpen&&<Advisor close={()=>setAdvisorOpen(false)} account={account}/>}
  {modal&&<Modal type={modal} close={()=>setModal(null)} go={(s)=>{setModal(null);go(s)}} notify={notify}/>}
 </div>
}

function Portal({account,ballots,go}:{account:Account;ballots:Ballot[];go:(s:Screen)=>void}){
 const open=ballots.reduce((s,x)=>s+x.incidents,0),entered=ballots.filter(x=>x.votes>0).length,scope=account.role==="district"?"Kadıköy geneli":account.role==="neighborhood"?`${account.neighborhood} Mahallesi`:account.school!;
 const modules:[Screen,string,string,React.ReactNode][]=[
  ["dashboard","Operasyon özeti",`${ballots.length} sandığın canlı durumunu aç`,<BarChart3/>],
  ["morning","Sabah operasyonu","07.00 hazırlık ve görevli teyitleri",<ClipboardCheck/>],
  ["ballots","Sandık vaka dosyaları","Süreç, olay, tutanak ve denetim",<FileText/>],
  ["incidents","Olay ve itiraz merkezi",`${open} açık kayıt`,<AlertTriangle/>],
  ["ocr","Tutanak OCR","Fotoğrafı okut, doğrula ve onayla",<Camera/>],
  ["results","Kümül seçim sonuçları",`${entered} tutanak sisteme girildi`,<BarChart3/>]
 ];
 return <><section className="portalHero"><div className="portalLogo"><span>☀</span><b>İYİ PARTİ</b><small>KADIKÖY İLÇE BAŞKANLIĞI</small></div><div><small>14 MAYIS 2023 MODELİ · OPERASYON SİMÜLASYONU</small><h1>Sandığa sahip çık.<br/>Sonucu güvenle doğrula.</h1><p>08.00 oy verme başlangıcından, 17.00 kapanış ve sayım sürecine kadar tüm operasyon tek merkezde.</p></div><aside><small>AKTİF PROFİL</small><b>{account.name}</b><span>{roleName[account.role]} · {scope}</span><em><CheckCircle2/> Sistem çevrimiçi</em></aside></section><section className="portalGrid">{modules.map(([screen,title,sub,icon])=><button key={screen} onClick={()=>go(screen)}><i>{icon}</i><span><b>{title}</b><small>{sub}</small></span><ChevronRight/></button>)}</section><div className="sourceNote"><ShieldCheck/><span><b>Gerçekçi veri temeli</b><small>YSK 2023: Kadıköy’de 1.050 sandık ve 389.092 seçmen. Demo sandık akışı bu ölçeğe göre modellenmiştir.</small></span></div></>
}

function Login({user,pass,err,setUser,setPass,login}:{user:string;pass:string;err:string;setUser:(x:string)=>void;setPass:(x:string)=>void;login:(e:React.FormEvent)=>void}){
 return <main className="login"><section className="intro"><div className="partyLockup"><span>☀</span><b>İYİ PARTİ</b><small>KADIKÖY İLÇE BAŞKANLIĞI</small></div><div className="logo">K360</div><h1>Sandığa sahip çık.<br/>Sonucu güvenle doğrula.</h1><p>İYİ Parti Kadıköy seçim koordinasyonu için okul, mahalle ve ilçe bazlı güvenli operasyon platformu.</p><span><ShieldCheck/>Okul, mahalle ve ilçe bazlı yetki</span><span><FileText/>Gerçek fotoğraf okuma ve doğrulama</span><span><BarChart3/>Ortak ve tutarlı kümül sonuçlar</span></section><form onSubmit={login} className="loginCard"><div className="lock"><ShieldCheck/></div><small>İYİ KADIKÖY360</small><h2>Operasyon merkezine giriş</h2><p>Size tanımlanan kullanıcı bilgileriyle devam edin.</p><label>Kullanıcı adı<input autoComplete="username" value={user} onChange={e=>setUser(e.target.value)}/></label><label>Şifre<input autoComplete="current-password" type="password" value={pass} onChange={e=>setPass(e.target.value)}/></label>{err&&<div className="error">{err}</div>}<button className="primary">Giriş yap</button></form></main>
}
function Dashboard({go,openMetric,ballots,account}:{go:(s:Screen)=>void;openMetric:(m:string)=>void;ballots:Ballot[];account:Account}){
 const total=ballots.length,entered=ballots.filter(x=>x.votes>0).length,approved=ballots.filter(x=>x.result==="Onaylandı").length,openIncidents=ballots.reduce((s,x)=>s+x.incidents,0),critical=ballots.filter(x=>x.critical&&x.incidents>0).length,resolved=ballots.reduce((s,x)=>s+(x.incidentRecords??[]).filter(r=>r.status==="Çözüldü").length,0);
 const groups:Array<{title:string;items:Array<[string,number]>}>=[
  {title:"Sabah operasyonu",items:[["Toplam sandık",total],["Görevli teyidi tamamlanan",ballots.filter(x=>x.officer==="Görevli geldi").length],["Görevli eksik",ballots.filter(x=>x.officer==="Görevli eksik").length],["Geç kalan",ballots.filter(x=>x.officer==="Geç kaldı").length],["Yedek görevli bekleyen",ballots.filter(x=>x.officer==="Yedek bekleniyor").length],["Sabah kontrolü yapılmayan",ballots.filter(x=>x.morning==="Kontrol bekliyor").length]]},
  {title:"Oy verme süreci",items:[["Oy verme başladı",ballots.filter(x=>x.voting.includes("başladı")||x.voting.includes("devam")||x.voting.includes("sona")).length],["Hazırlık devam ediyor",ballots.filter(x=>x.voting==="Hazırlık devam ediyor").length],["Başlaması geciken",ballots.filter(x=>x.voting==="Başlaması gecikti").length],["Aktif olay bulunan",ballots.filter(x=>x.incidents>0).length]]},
  {title:"Kapanış ve sayım",items:[["Oy verme tamamlandı",ballots.filter(x=>x.voting==="Oy verme sona erdi").length],["Sayıma geçen",ballots.filter(x=>x.counting!=="Sayım bekliyor").length],["Sayım bekleyen",ballots.filter(x=>x.counting==="Sayım bekliyor").length],["Hâlen sayım devam eden",ballots.filter(x=>x.counting.includes("devam")||x.counting==="Sayım başladı").length],["Sayımı tamamlanan",ballots.filter(x=>x.counting==="Sayım tamamlandı").length]]},
  {title:"Tutanak ve sonuç",items:[["Tutanak beklenen",ballots.filter(x=>x.result==="Tutanak bekleniyor").length],["Tutanak girilen",entered],["Kullanıcı doğrulaması bekleyen",ballots.filter(x=>x.result==="Kullanıcı doğrulaması bekliyor").length],["Revizyon istenen",ballots.filter(x=>x.result==="Revizyon istendi").length],["Onaylanan",approved]]},
  {title:"Olay ve itirazlar",items:[["Olay bulunan sandık",ballots.filter(x=>x.incidents>0).length],["Açık olay",openIncidents],["Kritik olay",critical],["Çözülen / kapatılan",resolved]]},
 ];
 const scope=account.role==="district"?"Kadıköy geneli":account.role==="neighborhood"?`${account.neighborhood} Mahallesi`:account.school!;
 return <><Title over="29 TEMMUZ 2026 · CANLI" title="Seçim operasyon merkezi" sub={`${scope} kapsamındaki ${total} sandığın canlı görünümü`}/>
 <div className="roleBanner"><div><small>{roleName[account.role].toLocaleUpperCase("tr")}</small><b>Düzenleme kapsamı: {scope}</b></div><span><RefreshCw/> Tek veri kaynağı · şimdi</span></div>
 <section className="quickActions">
  <button onClick={()=>go("morning")}><ClipboardCheck/><span><b>Sabah kontrolü</b><small>{ballots.filter(x=>x.morning==="Kontrol bekliyor").length} sandık bekliyor</small></span><ChevronRight/></button>
  <button onClick={()=>go("incidents")}><AlertTriangle/><span><b>Olay merkezi</b><small>{openIncidents} açık · {critical} kritik</small></span><ChevronRight/></button>
  <button onClick={()=>go("results")}><BarChart3/><span><b>Kümül seçim sonuçları</b><small>{entered} tutanak girildi</small></span><ChevronRight/></button>
 </section>
 <div className="completion"><div><b>Kapsam tamamlanma durumu</b><strong>%{total?Math.round(approved/total*100):0}</strong></div><p>Toplam {total} sandığın {approved} tanesi onaylandı. {total-entered} sandıkta tutanak bekleniyor.</p><em><span style={{width:`${total?approved/total*100:0}%`}}/></em><button onClick={()=>openMetric("Tutanak beklenen")}>Eksik sandıkları görüntüle <ChevronRight/></button></div>
 {groups.map((g,gi)=><section className="panel metricPanel" key={g.title}><Head title={g.title} sub={`${g.items.length} anlık gösterge`} icon={gi===4?<AlertTriangle/>:<BarChart3/>}/><div className="metricGrid">{g.items.map(([name,value])=><button className={name.includes("Kritik")||name.includes("eksik")?"dangerMetric":""} onClick={()=>openMetric(name)} key={name}><span>{name}<ChevronRight/></span><b>{value.toLocaleString("tr-TR")}</b><small>%{total?Math.round(value/total*100):0} · canlı veriden</small></button>)}</div></section>)}
 </>;
}
function Drilldown({metric,ballots,query,setQuery,openBallot}:{metric:string;ballots:Ballot[];query:string;setQuery:(x:string)=>void;openBallot:(id:string)=>void}){
 const match=(x:Ballot)=>metric==="Toplam sandık"||metric==="Görevli teyidi tamamlanan"&&x.officer==="Görevli geldi"||metric==="Görevli eksik"&&x.officer==="Görevli eksik"||metric==="Geç kalan"&&x.officer==="Geç kaldı"||metric==="Yedek görevli bekleyen"&&x.officer==="Yedek bekleniyor"||metric==="Sabah kontrolü yapılmayan"&&x.morning==="Kontrol bekliyor"||metric==="Hazırlık devam ediyor"&&x.voting==="Hazırlık devam ediyor"||metric==="Başlaması geciken"&&x.voting==="Başlaması gecikti"||metric==="Oy verme tamamlandı"&&x.voting==="Oy verme sona erdi"||metric==="Sayıma geçen"&&x.counting!=="Sayım bekliyor"||metric==="Sayım bekleyen"&&x.counting==="Sayım bekliyor"||metric==="Hâlen sayım devam eden"&&x.counting.includes("devam")||metric==="Sayımı tamamlanan"&&x.counting==="Sayım tamamlandı"||metric==="Tutanak beklenen"&&x.result==="Tutanak bekleniyor"||metric==="Tutanak girilen"&&x.votes>0||metric==="Kullanıcı doğrulaması bekleyen"&&x.result==="Kullanıcı doğrulaması bekliyor"||metric==="Revizyon istenen"&&x.result==="Revizyon istendi"||metric==="Onaylanan"&&x.result==="Onaylandı"||(metric==="Aktif olay bulunan"||metric==="Olay bulunan sandık"||metric==="Açık olay")&&x.incidents>0||metric==="Kritik olay"&&x.critical&&x.incidents>0||metric==="Çözülen / kapatılan"&&(x.incidentRecords??[]).some(r=>r.status==="Çözüldü")||metric==="Oy verme başladı"&&(x.voting.includes("başladı")||x.voting.includes("devam")||x.voting.includes("sona"));
 const visible=ballots.filter(match),groups=[...new Set(visible.map(x=>x.neighborhood))].map(n=>({name:n,count:visible.filter(x=>x.neighborhood===n).length}));
 return <><Crumbs items={["Kadıköy",metric]}/><Title over="KATEGORİ DETAYI" title={metric} sub={`${visible.length} sandık · mahalle → okul → sandık kırılımı`}/><section className="panel"><div className="searchWrap"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Sandık, okul veya mahalle ara"/></div><h3>Mahallelere göre dağılım</h3>{groups.length?groups.map(g=><details className="group" key={g.name} open><summary><MapPin/><span><b>{g.name} Mahallesi</b><small>{g.count} sandık</small></span><ChevronRight/></summary><div>{[...new Set(visible.filter(x=>x.neighborhood===g.name).map(x=>x.school))].map(s=><div className="schoolGroup" key={s}><b><School/> {s}</b>{visible.filter(x=>x.school===s).map(x=><button key={x.id} onClick={()=>openBallot(x.id)}><span><strong>Sandık {x.id}</strong><small>{x.counting} · {x.result}</small></span>{x.incidents>0&&<i>{x.incidents} olay</i>}<ChevronRight/></button>)}</div>)}</div></details>):<Empty text="Bu kategoride sandık bulunmuyor"/>}</section></>
}
function BallotList({ballots,query,setQuery,openBallot,filterOpen,setFilterOpen}:{ballots:Ballot[];query:string;setQuery:(x:string)=>void;openBallot:(id:string)=>void;filterOpen:boolean;setFilterOpen:(x:boolean)=>void}){
 return <><Title over="VAKA YÖNETİMİ" title="Sandık vaka dosyaları" sub="Her sandığın tüm seçim günü sürecini tek dosyada izleyin"/><section className="panel"><div className="listTools"><div className="searchWrap"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Sandık, okul veya mahalle ara"/></div><button onClick={()=>setFilterOpen(!filterOpen)}><Filter/> Filtrele</button></div>{filterOpen&&<div className="filters"><button>Mahalle: Tümü</button><button>Sayım: Tümü</button><button>Olay: Tümü</button><button>Sonuç: Tümü</button></div>}<div className="caseList">{ballots.map(x=><button className="case" onClick={()=>openBallot(x.id)} key={x.id}><i className={x.critical?"red":x.result==="Onaylandı"?"green":"amber"}><FileText/></i><span><b>Sandık {x.id}</b><small>{x.neighborhood} · {x.school}</small><em>{x.counting} · {x.result}</em></span>{x.incidents>0&&<mark>{x.incidents}</mark>}<ChevronRight/></button>)}</div></section></>
}
function BallotDetail({ballot,tab,setTab,update,go,timeline}:{ballot:Ballot;tab:string;setTab:(x:string)=>void;update:(p:Partial<Ballot>)=>void;go:(s:Screen)=>void;timeline:Timeline[]}){
 const tabs=["Genel","Zaman çizelgesi","Olaylar","Tutanak","Sonuç","Denetim"];
 const records=ballot.incidentRecords??[],openRecords=records.filter(x=>x.status==="Açık");
 return <><Crumbs items={["Kadıköy",`${ballot.neighborhood} Mahallesi`,ballot.school,`Sandık ${ballot.id}`]}/><div className="caseHero"><div><small>SANDIK VAKA DOSYASI</small><h1>Sandık {ballot.id}</h1><p>{ballot.school} · {ballot.neighborhood}</p></div><span className={ballot.critical?"criticalTag":"liveTag"}>{ballot.critical?"Kritik takip":"Aktif"}</span></div><div className="caseTabs">{tabs.map(x=><button className={tab===x?"active":""} onClick={()=>setTab(x)} key={x}>{x}</button>)}</div>
 {tab==="Genel"&&<><section className="panel statusCards"><div><small>GÖREVLİ</small><b>{ballot.officer}</b></div><div><small>OY VERME</small><b>{ballot.voting}</b></div><div><small>SAYIM</small><b>{ballot.counting}</b></div><div><small>TUTANAK DURUMU</small><b>{ballot.result}</b></div></section><section className="panel"><Head title="Hızlı durum güncelle" sub="08.00–17.00 seçim günü sırasına göre doğrulanır" icon={<RefreshCw/>}/><div className="actionGrid"><button onClick={()=>update({officer:"Görevli geldi",morning:"Hazırlık tamamlandı"})}><Check/> Görevli teyidi</button><button onClick={()=>update({officer:"Görevli geldi",morning:"Hazırlık tamamlandı",voting:"Oy verme başladı"})}><Check/> 08.00 oy verme başladı</button><button onClick={()=>update({officer:"Görevli geldi",morning:"Hazırlık tamamlandı",voting:"Oy verme sona erdi",counting:"Sayım devam ediyor"})}><Clock/> 17.00 sayım başladı</button><button className="warnAction" onClick={()=>go("incidentNew")}><AlertTriangle/> Olay / itiraz ekle</button><button onClick={()=>go("ocr")}><Camera/> Tutanak yükle</button></div></section><section className="panel"><Head title="Açık takipler" sub={`${openRecords.length} olay veya itiraz`} icon={<AlertCircle/>}/>{openRecords.length?openRecords.map(r=><button className="incidentRow" onClick={()=>setTab("Olaylar")} key={r.id}><AlertTriangle/><span><b>{r.category}</b><small>{r.priority} · {r.description}</small></span><ChevronRight/></button>):<Empty text="Açık olay bulunmuyor"/>}</section></>}
 {tab==="Zaman çizelgesi"&&<section className="panel timeline">{timeline.map((x,i)=><div key={x.title}><i className={i===0?"now":""}/><span><b>{x.title}</b><small>{x.who} · Bugün {x.time}</small>{x.note&&<p>{x.note}</p>}</span></div>)}</section>}
 {tab==="Olaylar"&&<section className="panel"><button className="primary noTop" onClick={()=>go("incidentNew")}><Plus/> Yeni olay veya itiraz</button>{records.length?records.map(r=><div className="incidentCard" key={r.id}><div><AlertTriangle/><b>{r.category}</b><span>{r.priority.toLocaleUpperCase("tr")}</span></div><p>{r.description}</p>{(r.party||r.votes)&&<p><b>İtiraz detayı:</b> {r.party||"Belirtilmedi"} · {r.votes||"0"} oy</p>}<small>Açan: {r.createdBy} · {r.createdAt} · Durum: {r.status}</small>{r.status==="Açık"&&<button onClick={()=>{const next=records.map(x=>x.id===r.id?{...x,status:"Çözüldü" as const,resolvedAt:new Date().toLocaleTimeString("tr-TR",{hour:"2-digit",minute:"2-digit"})}:x);update({incidentRecords:next,incidents:next.filter(x=>x.status==="Açık").length,critical:next.some(x=>x.status==="Açık"&&x.priority==="Kritik")})}}>Çözüldü olarak işaretle</button>}</div>):<Empty text="Bu sandıkta olay bulunmuyor"/>}</section>}
 {tab==="Tutanak"&&<section className="panel"><Head title="Tutanak ve OCR" sub={ballot.result} icon={<FileText/>}/>{ballot.votes?<div className="compare"><div><small>OCR İLK DEĞER</small><b>Geçerli oy: {ballot.votes+2}</b></div><ChevronRight/><div><small>ONAYLANAN DEĞER</small><b>Geçerli oy: {ballot.votes}</b></div></div>:<Empty text="Henüz tutanak yüklenmedi"/>}<button className="primary" onClick={()=>go("ocr")}><Camera/> {ballot.votes?"Tutanağı yeniden incele":"Tutanak yükle"}</button></section>}
 {tab==="Sonuç"&&<section className="panel"><Head title="Sandık sonucu" sub="Yalnızca onaylı sonuçlar kümüle dahil edilir" icon={<BarChart3/>}/>{ballot.votes?<><div className="resultTotal"><span><small>GEÇERLİ OY</small><b>{ballot.votes}</b></span><span><small>GEÇERSİZ OY</small><b>{ballot.invalid??0}</b></span></div>{Object.entries(ballot.parties??{}).map(([name,votes])=><div className="resultLine" key={name}><span>{name}</span><b>{votes}</b><em><i style={{width:`${ballot.votes?votes/ballot.votes*100:0}%`}}/></em></div>)}</>:<Empty text="Kesinleşmiş sonuç bulunmuyor"/>}</section>}
 {tab==="Denetim"&&<section className="panel audit">{timeline.slice(0,4).map(x=><div key={x.title}><ShieldCheck/><span><b>{x.title}</b><small>{x.who} · {x.time} · Sunucu zamanı doğrulandı</small></span></div>)}</section>}
 </>;
}
function Morning({ballots,update,openBallot}:{ballots:Ballot[];update:(id:string,p:Partial<Ballot>)=>void;openBallot:(id:string)=>void}){
 const arrived=ballots.filter(x=>x.officer==="Görevli geldi").length,missing=ballots.filter(x=>x.officer==="Görevli eksik").length,late=ballots.filter(x=>x.officer==="Geç kaldı").length,reserve=ballots.filter(x=>x.officer==="Yedek bekleniyor").length;
 return <><Title over="SABAH OPERASYONU · TARİHÇE" title="Sabah kontrol listesi" sub="Oy verme başladıktan sonra sabah kayıtları kilitlenir; düzeltme sandık vaka dosyasından denetim kaydıyla yapılır"/><div className="phaseBanner"><Clock/><span><b>Mevcut simülasyon aşaması: 17.00 sonrası sayım</b><small>08.00 başlangıç kayıtları artık tarihçe görünümündedir.</small></span></div><div className="summaryStrip"><span><b>{arrived}</b><small>Görevli tamam</small></span><span><b>{missing}</b><small>Eksik</small></span><span><b>{late}</b><small>Geç kalan</small></span><span><b>{reserve}</b><small>Yedek bekleyen</small></span></div><section className="panel morningList">{ballots.map(x=><div key={x.id}><button onClick={()=>openBallot(x.id)}><b>Sandık {x.id}</b><small>{x.school}</small></button><select value={x.officer} disabled title="08.00 sonrasında sabah kaydı kilitlidir" onChange={e=>update(x.id,{officer:e.target.value})}><option>Görevli geldi</option><option>Görevli eksik</option><option>Geç kaldı</option><option>Yedek bekleniyor</option></select></div>)}</section></>
}
function Incidents({ballots,openBallot,create}:{ballots:Ballot[];openBallot:(id:string)=>void;create:()=>void}){
 const active=ballots.filter(x=>x.incidents>0),open=active.reduce((s,x)=>s+x.incidents,0),critical=active.filter(x=>x.critical).length;
 return <><Title over="OLAY MERKEZİ" title="Olaylar ve itirazlar" sub="Yetki kapsamınızdaki açık vakalar"/><button className="primary topAction" onClick={create}><Plus/> Yeni olay oluştur</button><div className="incidentStats"><span><b>{open}</b>Açık olay</span><span><b>{critical}</b>Kritik sandık</span><span><b>{active.length}</b>Takip edilen sandık</span></div><section className="panel">{active.length?active.map(x=>{const latest=[...(x.incidentRecords??[])].reverse().find(r=>r.status==="Açık");return <button className="incidentListItem" onClick={()=>openBallot(x.id)} key={x.id}><i className={x.critical?"red":"amber"}><AlertTriangle/></i><span><b>{latest?.category??"Olay veya itiraz"}</b><small>Sandık {x.id} · {x.school}</small><em>{latest?.description??`${x.incidents} açık kayıt`} · {x.updated}</em></span><ChevronRight/></button>}):<Empty text="Yetki kapsamınızda açık olay bulunmuyor"/>}</section></>
}
function IncidentForm({ballots,selectedId,setSelectedId,incident,setIncident,save}:{ballots:Ballot[];selectedId:string;setSelectedId:(x:string)=>void;incident:{category:string;priority:string;description:string;party:string;votes:string};setIncident:(x:any)=>void;save:()=>void}){
 return <><Title over="YENİ VAKA KAYDI" title="Olay veya itiraz oluştur" sub="Kayıt seçilen sandığa ve olay merkezine aynı anda işlenir"/><section className="panel form"><label>Sandık<select value={ballots.some(x=>x.id===selectedId)?selectedId:""} onChange={e=>setSelectedId(e.target.value)}><option value="" disabled>Yetki kapsamından sandık seçin</option>{ballots.map(x=><option value={x.id} key={x.id}>Sandık {x.id} · {x.school}</option>)}</select></label><label>Olay kategorisi<select value={incident.category} onChange={e=>setIncident({...incident,category:e.target.value})}><option>Bir parti veya adaya yazılan oya itiraz</option><option>Görevli eksikliği</option><option>Mühür sorunu</option><option>Sayım uyuşmazlığı</option><option>Tutanak uyuşmazlığı</option><option>Güvenlik olayı</option></select></label><label>Öncelik<select value={incident.priority} onChange={e=>setIncident({...incident,priority:e.target.value})}><option>Normal</option><option>Yüksek</option><option>Kritik</option></select></label><label>Açıklama<textarea rows={5} value={incident.description} onChange={e=>setIncident({...incident,description:e.target.value})} placeholder="Olayı açık ve doğrulanabilir biçimde anlatın"/></label><div className="fieldGrid"><label>İtiraz edilen parti / aday<input value={incident.party} onChange={e=>setIncident({...incident,party:e.target.value})}/></label><label>İtiraz edilen oy<input inputMode="numeric" value={incident.votes} onChange={e=>setIncident({...incident,votes:e.target.value})}/></label></div><label className="file light"><Upload/> Fotoğraf veya belge ekle<input hidden type="file" accept="image/*,.pdf"/></label><button className="primary" disabled={!ballots.some(x=>x.id===selectedId)} onClick={save}>Olayı kaydet ve sorumluya bildir</button></section></>
}
function Results({ballots,scoped,account,go,openBallot}:{ballots:Ballot[];scoped:Ballot[];account:Account;go:(s:Screen)=>void;openBallot:(id:string)=>void}){
 const approved=ballots.filter(x=>x.result==="Onaylandı"&&x.votes>0),entered=ballots.filter(x=>x.votes>0),totalVotes=approved.reduce((s,x)=>s+x.votes,0),percent=ballots.length?Math.round(approved.length/ballots.length*1000)/10:0;
 const partyTotals=approved.reduce<Record<string,number>>((all,b)=>{Object.entries(b.parties??{}).forEach(([name,votes])=>{all[name]=(all[name]??0)+votes});return all},{});
 const queue=scoped.filter(x=>x.result!=="Onaylandı"&&x.votes>0);
 const scope=account.role==="district"?"Kadıköy geneli":account.role==="neighborhood"?`${account.neighborhood} Mahallesi`:account.school!;
 return <><Title over="ONAYLI SONUÇLAR" title="Seçim sonuçları" sub={`${approved.length} / ${ballots.length} sandık onaylandı · ${entered.length} tutanak girildi`}/><div className="roleBanner"><div><small>GÖRÜNÜM</small><b>Kümül sonuçlar tüm kullanıcılar için Kadıköy genelidir</b></div><span>İşlem kapsamı: {scope}</span></div><div className="completion resultCompletion"><div><b>Kadıköy geneli</b><strong>%{percent.toLocaleString("tr-TR")}</strong></div><em><span style={{width:`${percent}%`}}/></em><small>{approved.length} onaylı · {entered.length} girilmiş tutanak · son güncelleme şimdi</small></div><section className="panel"><Head title="Parti dağılımı" sub={`${totalVotes.toLocaleString("tr-TR")} geçerli oy · yalnızca onaylı sandıklar`} icon={<BarChart3/>}/>{Object.keys(partyTotals).length?Object.entries(partyTotals).sort((a,b)=>b[1]-a[1]).map(([name,votes])=>{const share=totalVotes?votes/totalVotes*100:0;return <div className="resultLine big" key={name}><span>{name} <small>%{share.toLocaleString("tr-TR",{maximumFractionDigits:1})}</small></span><b>{votes.toLocaleString("tr-TR")}</b><em><i style={{width:`${share}%`}}/></em></div>}):<Empty text="Henüz onaylı sonuç bulunmuyor"/>}</section><section className="panel"><Head title="Yetki kapsamındaki onay kuyruğu" sub={`${queue.length} işlem bekleyen tutanak`} icon={<Clock/>}/>{queue.length?queue.map(x=><button className="queue" onClick={()=>openBallot(x.id)} key={x.id}><FileText/><span><b>Sandık {x.id}</b><small>{x.result}</small></span><ChevronRight/></button>):<Empty text="Yetki kapsamınızda işlem bekleyen tutanak bulunmuyor"/>}<button className="primary" onClick={()=>go("ocr")}><Camera/> Yeni tutanak yükle</button></section></>
}
function OcrFlow({image,choose,reading,read,err,step,setStep,ocr,setOcr,allowedBallots,finish}:{image:string;choose:(f?:File)=>void;reading:boolean;read:()=>void;err:string;step:number;setStep:(x:number)=>void;ocr:Ocr;setOcr:(x:Ocr)=>void;allowedBallots:Ballot[];finish:()=>void}){
 return <><Title over="TUTANAK İŞLEMLERİ" title="Tutanak yükle ve doğrula" sub="Sonuç hiçbir zaman kullanıcı onayı olmadan kesinleşmez"/><div className="steps">{["1 Fotoğraf","2 Okul","3 Sandık","4 Oylar","5 Son onay"].map((x,i)=><span className={step>=i+1?"on":""} key={x}>{x}</span>)}</div>
 {step===1&&<section className="panel upload">{image?<img src={image} alt="Tutanak"/>:<div className="drop"><Camera/><b>Tutanak fotoğrafı çekin</b><p>Belgenin dört köşesi görünmeli; fotoğraf net ve gölgesiz olmalı.</p></div>}<div className="qualityChecks"><span><Check/> Dört köşe</span><span><Check/> Netlik</span><span><Check/> Işık</span></div><label className="file"><Camera/>Kamerayı aç<input hidden type="file" accept="image/*" capture="environment" onChange={e=>choose(e.target.files?.[0])}/></label><label className="file light"><Upload/>Galeriden seç<input hidden type="file" accept="image/*" onChange={e=>choose(e.target.files?.[0])}/></label>{image&&<button className="primary" disabled={reading} onClick={read}>{reading?"Fotoğraf gerçekten okunuyor…":"Tutanağı OCR ile oku"}</button>}{err&&<div className="error">{err}</div>}</section>}
 {step===2&&<Confirm title="Okulu teyit edin" label="Tespit edilen okul" value={ocr.school} set={v=>setOcr({...ocr,school:v})} next={()=>setStep(3)}/>}
 {step===3&&<section className="panel confirm"><ShieldCheck/><h2>Sandık numarasını teyit edin</h2><p>Yalnızca yetki kapsamınızdaki sandıklara tutanak kaydedebilirsiniz.</p><label>Yetkili sandık<select value={allowedBallots.some(x=>x.id===ocr.ballotBox)?ocr.ballotBox:""} onChange={e=>{const b=allowedBallots.find(x=>x.id===e.target.value);setOcr({...ocr,ballotBox:e.target.value,school:b?.school??ocr.school,neighborhood:b?.neighborhood??ocr.neighborhood})}}><option value="" disabled>Sandık seçin</option>{allowedBallots.map(x=><option value={x.id} key={x.id}>Sandık {x.id} · {x.school}</option>)}</select></label>{ocr.ballotBox&&!allowedBallots.some(x=>x.id===ocr.ballotBox)&&<div className="error">OCR sandık numarası yetki kapsamınızda değil. Doğru sandığı listeden seçin.</div>}<button className="primary" disabled={!allowedBallots.some(x=>x.id===ocr.ballotBox)} onClick={()=>setStep(4)}>Doğru, devam et</button></section>}
 {step===4&&<Votes ocr={ocr} setOcr={setOcr} next={()=>setStep(5)}/>}
 {step===5&&<FinalReview image={image} ocr={ocr} edit={()=>setStep(4)} finish={finish}/>}
 {step===6&&<section className="panel success"><CheckCircle2/><h2>Doğrulama tamamlandı</h2><p>Onaylı sandık sonucu kaydedildi; tutanak sayısı ve kümül oy dağılımı güncellendi.</p><button className="primary" onClick={()=>{setStep(1);setOcr(blank)}}>Yeni tutanak yükle</button></section>}</>
}
function Votes({ocr,setOcr,next}:{ocr:Ocr;setOcr:(x:Ocr)=>void;next:()=>void}){
 const party=(i:number,k:"name"|"votes",v:string)=>{const p=[...ocr.parties];p[i]={...p[i],[k]:k==="votes"?(v===""?null:Number(v)):v};setOcr({...ocr,parties:p})};
 const partyTotal=ocr.parties.reduce((s,p)=>s+(p.votes??0),0), mismatch=ocr.validVotes!==null&&partyTotal!==ocr.validVotes;
 return <section className="panel form"><div className="confidence"><ShieldCheck/><span><b>OCR güveni: %{ocr.confidence||0}</b><small>Sarı alanları fotoğrafla karşılaştırın.</small></span></div>{ocr.confidence<70&&<div className="warning"><AlertTriangle/>Okuma güveni düşük. Sistem rakam tahmin etmez; boş alanları manuel girin.</div>}<div className="fieldGrid">{([["Kayıtlı seçmen","registeredVoters"],["Oy kullanan","voters"],["Geçerli oy","validVotes"],["Geçersiz oy","invalidVotes"]] as const).map(([l,k])=><label className={ocr[k]===null?"lowConfidence":""} key={k}>{l}<input inputMode="numeric" value={ocr[k]??""} onChange={e=>setOcr({...ocr,[k]:e.target.value===""?null:Number(e.target.value)})}/></label>)}</div><h3>Parti / aday oyları</h3>{ocr.parties.length===0&&<div className="warning">Parti satırları okunamadı. Fotoğrafa bakarak manuel satır ekleyin.</div>}{ocr.parties.map((p,i)=><div className="party" key={i}><input value={p.name} placeholder="Parti / aday" onChange={e=>party(i,"name",e.target.value)}/><input inputMode="numeric" value={p.votes??""} placeholder="Oy" onChange={e=>party(i,"votes",e.target.value)}/></div>)}<button className="light add" onClick={()=>setOcr({...ocr,parties:[...ocr.parties,{name:"",votes:null}]})}>+ Satır ekle</button>{mismatch&&<div className="error"><AlertTriangle/> Parti/aday toplamı ({partyTotal}) ile geçerli oy ({ocr.validVotes}) uyuşmuyor.</div>}<button className="primary" disabled={mismatch||ocr.validVotes===null} onClick={next}>Rakamları kontrol ettim</button></section>
}
function Confirm({title,label,value,set,next}:{title:string;label:string;value:string;set:(v:string)=>void;next:()=>void}){return <section className="panel confirm"><ShieldCheck/><h2>{title}</h2><p>OCR sonucunu gerçek tutanakla karşılaştırın ve gerekirse düzeltin.</p><label>{label}<input value={value} onChange={e=>set(e.target.value)} placeholder="Okunamadı — manuel girin"/></label><button className="primary" disabled={!value.trim()} onClick={next}>Doğru, devam et</button></section>}
function FinalReview({image,ocr,edit,finish}:{image:string;ocr:Ocr;edit:()=>void;finish:()=>void}){return <section className="panel finalReview"><h2>Son onay özeti</h2><p>Fotoğrafı ve girilen verileri son kez karşılaştırın.</p><div className="reviewSplit"><img src={image} alt="Tutanak"/><div><span><small>OKUL</small><b>{ocr.school}</b></span><span><small>SANDIK</small><b>{ocr.ballotBox}</b></span><span><small>GEÇERLİ / GEÇERSİZ</small><b>{ocr.validVotes} / {ocr.invalidVotes}</b></span>{ocr.parties.map(p=><span key={p.name}><small>{p.name||"Parti / aday"}</small><b>{p.votes}</b></span>)}</div></div><label className="approval"><input type="checkbox" required/> Fotoğraf ile verileri karşılaştırdım; bilgilerin doğru olduğunu onaylıyorum.</label><div className="dual"><button className="light" onClick={edit}>Düzelt</button><button className="primary" onClick={finish}>Onaya gönder</button></div></section>}
function UsersPage({accounts,active,switchAccount,edit,notify}:{accounts:Account[];active:Account;switchAccount:(a:Account)=>void;edit:()=>void;notify:(x:string)=>void}){return <><Title over="YETKİ YÖNETİMİ" title="Üç operasyon profili" sub="Her profil yalnızca kendi operasyon kapsamını düzenler; kümül sonuçları herkes görür"/><div className="dual topDual"><button className="light" onClick={()=>notify("CSV şablonu indirilmeye hazırlandı.")}><Upload/> CSV içe aktar</button><button className="primary" onClick={edit}><Plus/> Kullanıcı ekle</button></div><section className="panel">{accounts.map(a=>{const scope=a.role==="district"?"Kadıköy geneli":a.role==="neighborhood"?`${a.neighborhood} Mahallesi`:a.school!;return <div className="role" key={a.username}><Users/><span><b>{a.name}</b><small>{roleName[a.role]} · {scope}</small></span><i>{active.username===a.username?"Aktif profil":"Hazır"}</i><button onClick={()=>switchAccount(a)}>{active.username===a.username?"Kullanılıyor":"Profile geç"}</button></div>})}</section></>}
function Notifications({ballots,openBallot}:{ballots:Ballot[];openBallot:(id:string)=>void}){
 const items=ballots.filter(x=>x.incidents>0||x.result!=="Onaylandı"||x.morning==="Kontrol bekliyor").map(x=>[x.critical?"Kritik olay açık":x.incidents>0?"Olay çözüm bekliyor":x.result!=="Onaylandı"?"Tutanak işlemi bekliyor":"Sabah kontrolü bekliyor",`Sandık ${x.id} · ${x.school}`,x.id,x.updated]);
 return <><Title over="BİLDİRİMLER" title="Operasyon bildirimleri" sub="Yetki kapsamınızdaki güncel işlem kayıtları"/><section className="panel notifications">{items.length?items.map(x=><button onClick={()=>openBallot(x[2])} key={x[0]+x[2]}><i><Bell/></i><span><b>{x[0]}</b><small>{x[1]}</small></span><time>{x[3]}</time><ChevronRight/></button>):<Empty text="İşlem gerektiren bildirim bulunmuyor"/>}</section></>
}
function Profile({account,accounts,scopeCount,switchAccount,logout}:{account:Account;accounts:Account[];scopeCount:number;switchAccount:(a:Account)=>void;logout:()=>void}){
 const scope=account.role==="district"?"Kadıköy geneli":account.role==="neighborhood"?`${account.neighborhood} Mahallesi`:account.school!;
 return <><Title over="HESABIM" title="Profil ve yetki görünümü" sub="Demo içinde üç rolü gerçek kapsamlarıyla inceleyebilirsiniz"/><section className="panel profileCard"><div className="bigAvatar">{account.name.slice(0,1)}</div><h2>{account.name}</h2><p>{roleName[account.role]} · {scope}</p><span><CheckCircle2/> Çevrimiçi</span></section><section className="panel profileRows"><div><b>Düzenlenebilir sandık</b><span>{scopeCount}</span></div><div><b>Kümül sonuç görünümü</b><span>Kadıköy geneli · salt okunur</span></div><div><b>Son senkronizasyon</b><span>Şimdi</span></div><div><b>Uygulama sürümü</b><span>3.0.0</span></div></section><section className="panel"><Head title="Rol önizleme" sub="Yetki sınırlarını kontrol etmek için profil değiştirin" icon={<UserCog/>}/>{accounts.map(a=><button className="queue" key={a.username} disabled={a.username===account.username} onClick={()=>switchAccount(a)}><Users/><span><b>{a.name}</b><small>{roleName[a.role]}</small></span><ChevronRight/></button>)}<button className="logout" onClick={logout}><LogOut/> Güvenli çıkış yap</button></section></>
}
function Advisor({close,account}:{close:()=>void;account:Account}){
 const[question,setQuestion]=useState(""),[image,setImage]=useState(""),[answer,setAnswer]=useState(""),[error,setError]=useState(""),[loading,setLoading]=useState(false);
 const scope=account.role==="district"?"Kadıköy geneli":account.role==="neighborhood"?`${account.neighborhood} Mahallesi`:account.school!;
 const suggestions=["Bu pusula geçerli mi?","Bir oya itiraz edilirse ne yapmalıyım?","Saat 20.00'de ilçe seçim kuruluna gitmem gerekir mi?"];
 function chooseAdvisorImage(file?:File){if(!file)return;const reader=new FileReader();reader.onload=()=>setImage(String(reader.result));reader.readAsDataURL(file)}
 async function ask(text=question){if(!text.trim())return;setQuestion(text);setLoading(true);setError("");setAnswer("");try{const response=await fetch("/api/advisor",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({question:text,image,role:roleName[account.role],scope})});const payload=await response.json();if(!response.ok)throw new Error(payload.error);setAnswer(payload.answer)}catch(e){setError(e instanceof Error?e.message:"Danışmana ulaşılamadı.")}finally{setLoading(false)}}
 return <div className="advisorShade" onClick={close}><aside className="advisorPanel" onClick={e=>e.stopPropagation()}><header><div><i><Bot/></i><span><b>İYİ Seçim Danışmanı</b><small>Belge destekli saha rehberi</small></span></div><button onClick={close}><X/></button></header><div className="advisorScope"><ShieldCheck/><span><b>{roleName[account.role]}</b><small>{scope}</small></span></div><div className="advisorIntro"><p>Seçim süreci, şikâyet/itiraz ve pusula değerlendirmesi hakkında sorun. Fotoğraf da ekleyebilirsiniz.</p><small>Yanıtlar karar yerine geçmez; tereddütte sandık kurulu kararı ve ilçe hukuk desteği esastır.</small></div>{!answer&&!loading&&<div className="advisorSuggestions">{suggestions.map(x=><button key={x} onClick={()=>ask(x)}>{x}<ChevronRight/></button>)}</div>}{image&&<div className="advisorImage"><img src={image} alt="Soruya eklenen pusula veya seçim belgesi"/><button onClick={()=>setImage("")}><X/></button></div>}{loading&&<div className="advisorThinking"><Bot/><span><b>Bilgi bankası kontrol ediliyor…</b><small>Görselde okunmayan ayrıntılar tahmin edilmeyecek.</small></span></div>}{answer&&<div className="advisorAnswer"><ShieldCheck/><p>{answer}</p></div>}{error&&<div className="error">{error}</div>}<div className="advisorComposer"><label title="Fotoğraf ekle"><ImagePlus/><input hidden type="file" accept="image/*" capture="environment" onChange={e=>chooseAdvisorImage(e.target.files?.[0])}/></label><textarea rows={2} value={question} onChange={e=>setQuestion(e.target.value)} placeholder="Sorunuzu yazın…" onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();ask()}}}/><button disabled={loading||!question.trim()} onClick={()=>ask()}><Send/></button></div></aside></div>
}
function Modal({type,close,go,notify}:{type:"user"|"settings"|"incident";close:()=>void;go:(s:Screen)=>void;notify:(x:string)=>void}){
 if(type==="settings")return <div className="modalShade" onClick={close}><aside className="drawer" onClick={e=>e.stopPropagation()}><div className="drawerHead"><b>İYİ KADIKÖY360</b><button onClick={close}><X/></button></div>{[["Ana operasyon menüsü","portal"],["İlçe operasyon merkezi","dashboard"],["Sabah kontrol listesi","morning"],["Sandık vaka dosyaları","ballots"],["Olay ve itiraz merkezi","incidents"],["Sonuçlar ve onay kuyruğu","results"],["Kullanıcı ve yetki yönetimi","users"],["Bildirimler","notifications"],["Profil ve bağlantı","profile"]].map(x=><button onClick={()=>go(x[1] as Screen)} key={x[0]}><ChevronRight/>{x[0]}</button>)}<hr/><button onClick={()=>notify("Denetim kayıtları görünümü açıldı.")}><ShieldCheck/>Denetim kayıtları</button><button onClick={()=>notify("Sistem ayarları görünümü açıldı.")}><Settings/>Sistem ayarları</button></aside></div>;
 return <div className="modalShade"><div className="dialog"><button className="close" onClick={close}><X/></button><UserCog/><h2>{type==="user"?"Kullanıcı ve yetki tanımı":"Olay işlemi"}</h2><label>Ad soyad<input defaultValue="Yeni kullanıcı"/></label><label>Rol<select defaultValue="Okul başkanı"><option>Okul başkanı</option><option>Mahalle başkanı</option><option>İlçe admini</option></select></label><label>Düzenleme kapsamı<select defaultValue="Bostancı Atatürk İlkokulu"><option>Bostancı Atatürk İlkokulu</option><option>Bostancı Mahallesi</option><option>Kadıköy geneli</option></select></label><label><input type="checkbox" defaultChecked disabled/> İlçe kümül sonuçlarını salt okunur görüntüler</label><button className="primary" onClick={()=>{close();notify("Kullanıcı rolü ve kapsamı kaydedildi.")}}>Kaydet</button></div></div>
}
function Crumbs({items}:{items:string[]}){return <div className="crumbs">{items.map((x,i)=><span key={x}>{x}{i<items.length-1&&<ChevronRight/>}</span>)}</div>}
function Title({over,title,sub}:{over:string;title:string;sub:string}){return <div className="title"><small>{over}</small><h1>{title}</h1><p>{sub}</p></div>}
function Head({title,sub,icon}:{title:string;sub:string;icon:React.ReactNode}){return <div className="head"><div><h2>{title}</h2><p>{sub}</p></div>{icon}</div>}
function Nav({active,on,icon,text,center}:{active:boolean;on:()=>void;icon:React.ReactNode;text:string;center?:boolean}){return <button className={`${active?"active":""} ${center?"center":""}`} onClick={on}>{icon}{text}</button>}
function Empty({text}:{text:string}){return <div className="empty"><FileText/><p>{text}</p></div>}
